name: Pack Chocolatey Package

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  pack:
    environment: Chocolatey Community
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Pack
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: pack

      - name: Install
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install zig --debug --verbose --source "'.;https://community.chocolatey.org/api/v2/'"

      - name: Check Zig Version
        run: |
          zig version

      - name: Set Chocolatey API Key
        uses: crazy-max/ghaction-chocolatey@v2
        if: github.ref_type == 'tag'
        with:
          args: apikey -y --key "${{ secrets.CHOCO_API_KEY }}" --source https://push.chocolatey.org/

      - name: Push To Chocolatey
        uses: crazy-max/ghaction-chocolatey@v2
        if: github.ref_type == 'tag'
        with:
          args: push zig.${{ github.ref_name }}.nupkg -s https://push.chocolatey.org/